### ISSUE TITLE
Haveno connection error

### ISSUE THREAD

**Issue by NeuraByte** [retoaccess1/haveno-reto#10]
![errr](https://github.com/user-attachments/assets/53b1efe3-6d05-4c43-a8b6-95f8da2820d7)
I installed the app for windows, but I always get this error, even though I have disabled virus programs, vpn, etc. I have deleted and reinstalled the app multiple times (local-roaming) but it still doesn't work.

**Comment by retoaccess1** [comment]
Something is messing with the tor setup. Please ask in the haveno matrix channels for support and maybe share your logs with woodser so he can look into this issue.

**Comment by k4r4b3y** [comment]
@NeuraByte join the MoneroTurko chat room: https://signal.group/#CjQKICUccbfPqIGYux906JmjTTY9TIplefrNHCNB-rNdOB7kEhDwqp9rYNPC4ccS0nROndI6
