### ISSUE TITLE
We did not receive a fIlter object from the seed nodes. . .

### ISSUE THREAD

**Issue by Eclypticon** [retoaccess1/haveno-reto#13]
![Haveno error](https://github.com/user-attachments/assets/f7a7ad05-825c-4d43-bb2f-f3ceb8192149)

Haveno-reto appears to connect to tor but there are no seed nodes. No amount of time seems to make any difference. I have had it up for days. I cannot make trades.

**Comment by xDaveN** [comment]
+1 same here

**Comment by boldsuck** [comment]
> Haveno-reto appears to connect to tor but there are no seed nodes. No amount of time seems to make any difference. I have had it up for days. I cannot make trades.

You Closed the warning and waited? If so, how many peers do you have?

**Comment by Eclypticon** [comment]
There is nothing there. No seed nodes available. I don't have any issues connecting to Tor in general. The Tor browser works fine for example.

**Comment by boldsuck** [comment]
> The Tor browser works fine for example.

This has nothing to do with Haveno's Tor binary, Tor browser has its own Tor binary.

**Comment by Eclypticon** [comment]
I've tried bridges and VPNs, but its not working. Under network it says no data available. Same problem on Debian.

**Comment by retoaccess1** [comment]
Please join the reto simplex so I can DM you a private onion to connect to.

**Comment by PrivacyPleb** [comment]
![Screenshot from 2024-07-31 18-48-23](https://github.com/user-attachments/assets/20ff671f-f9e6-4b30-af2e-da37038790ff)
![Screenshot from 2024-07-31 18-48-07](https://github.com/user-attachments/assets/073852c0-129b-493c-a741-c91bd1d7e867)
![Screenshot from 2024-07-31 18-53-45](https://github.com/user-attachments/assets/aae986c0-eced-4283-9e11-118ff6fdd975)


I'm having a similar issue AND i only see two offers in the whole app, making sure not to have " Show only offers that match my account" ticked. This happened after updating to the latest version.

**Comment by boldsuck** [comment]
Where is your problem? Everything is fine, you are connected in & out.
Filter: USD there are only 2 Buy offer atm. Put some in.
Warning !=Error, close it and you're done.

**Comment by privacyguy123** [comment]
> Please join the reto simplex so I can DM you a private onion to connect to.

I cannot seem to get SimpleX to connect to anything - does it not work behind a VPN?

**Comment by boldsuck** [comment]
The SimpleX network has adopted many design features from the Tor transport overlay network. Sending it through VPN, Tor or I2P is unnecessary and causes more problems than benefits. You can also choose private servers or run your own SMP server.
I simply added the [repo in F-droid](https://simplex.chat/fdroid/) and installed the app and [created a profile](https://simplex.chat/docs/guide/readme.html). This is easier than Signal/Molly or Telegram, no ID, phone number or similar.
