### ISSUE TITLE
Cannot invoke "monero.wallet.MoneroWallet.close(boolean)" because "wallet" is null

### ISSUE THREAD

**Issue by User00123** [retoaccess1/haveno-reto#15]
This error happened when booting up : 
Cannot invoke "monero.wallet.MoneroWallet.close(boolean)" because "wallet" is null
![h1](https://github.com/user-attachments/assets/91733f84-9fbd-4222-9bfd-07b27d62227a)
![h2](https://github.com/user-attachments/assets/c9bfb5c3-f61c-4c8b-b4ac-4c572b67f89b)

**Comment by Drew724** [comment]
Hello message support on telegram @Monero_Support_Dev for assistance.

**Comment by retoaccess1** [comment]
Fixed with v1.0.10
