### ISSUE TITLE
Wallet won't open

### ISSUE THREAD

**Issue by Nebuchadnezzar94** [retoaccess1/haveno-reto#17]
Hey, I keep getting this warning when I try to open haveno, how do I fix it:

"Warning
Could not open wallet 'haveno_XMR'. Please close Haveno, stop all monero-wallet-rpc processes, and restart Haveno.

Error message: Failed to open wallet"

**Comment by Nebuchadnezzar94** [comment]
I think I may have solved the issue. The daemon apparently interferes with haveno whenever you start it up. So when I killed it and restarted everything worked fine. However, there's still clearly an issue right? I shouldn't have to manually kill the processes every time should I?

**Comment by retoaccess1** [comment]
This issue has been reported before, looks like it happens when there are multiple rpc processes (from Haveno & GUI wallet for example) going on at the same time. In the future, please open software-related issues on the upstream haveno-dex repo.

**Comment by Githuber1-ai** [comment]
> I think I may have solved the issue. The daemon apparently interferes with haveno whenever you start it up. So when I killed it and restarted everything worked fine. However, there's still clearly an issue right? I shouldn't have to manually kill the processes every time should I?

What do you mean by the daemon? I am having the same problem?

**Comment by Githuber1-ai** [comment]
> This issue has been reported before, looks like it happens when there are multiple rpc processes (from Haveno & GUI wallet for example) going on at the same time. In the future, please open software-related issues on the upstream haveno-dex repo.


what exactly do you mean going on at the same time. I literally closed every other app, uninstalled some things I didn’t need and it’s still NOT working.


PLEASE HELP PLEASE PLEASE PLEASE!!!!!’
