### ISSUE TITLE
Can’t login

### ISSUE THREAD

**Issue by ghost** [retoaccess1/haveno-reto#19]
Earlier today, I clicked on the application and put in my password as usual. However, for some reason it says “Could not open wallet haveno xmr. Please close Haveno, stop all Monero wallet rpc processes and restart haveno.”

 I tried to login again, turn off and restart my computer, and more but it still doesn’t seem to be working. I have some Monero already deposited there. Please please please some one help me!!!! I don’t want to lose my hard earned Monero, PLEASE!!!!

![E5CAD6BA-C52B-449D-B6C3-7D6E33174299](https://github.com/user-attachments/assets/398f8762-bcec-401a-ab6e-c5689d51e0a8)

**Comment by retoaccess1** [comment]
Hello, this is fixed with the newest update which will hopefully be available within the next hour.
