### ISSUE TITLE
Maker and taker fees should be equal

### ISSUE THREAD

**Issue by johnnyboisssss** [retoaccess1/haveno-reto#27]
Maker and taker fees should be equal so as not to incentivize making or taking to avoid fees. Those who are happy with the current offers can take one at the same cost as someone who isn't satisfied and makes their own offer. It seems fair and will also incentivize making more offers, which will increase liquidity, since right now it's better to be a taker than a maker, but having more makers means more payments options, etc.

**Comment by retoaccess1** [comment]
Removed fee with 1.0.13
