### ISSUE TITLE
Ability to configure options at startup

### ISSUE THREAD

**Issue by FrankGrimes-ai** [retoaccess1/haveno-reto#28]
I can only change settings or configure bridges if  the prompt is triggered by something like a timeout. 

I'm currently experiencing extensive times to synchronizing with the monero mainnet and I'm not sure if this is due to the ddos or a poor bridge connection.

It would be good to see the option to configure startup settings in the loading screen.

**Comment by FrankGrimes-ai** [comment]
Just disconnect your Internet connection to get the tor settings

**Comment by SirCreatus** [comment]
I have done so to get the alert that "You lost the connection to all P2P network peers."

Then reconnect internet connection and wait about ten minutes to try again and get the same issue:

Cannot invoke "monero.wallet.MoneroWallet.exportMultisigHex()" because "this.wallet" is null
