### ISSUE TITLE
Enhancement: Support importing Bisq fiat accounts

### ISSUE THREAD

**Issue by alecov** [retoaccess1/haveno-reto#30]
As per the title. Very useful when you have many accounts already registered with age information and desire to reuse them in Haveno.

Tried to naively copy the `AccountAgeWitnessStore` file but loading failed with protobuf errors.

**Comment by XMRZombie** [comment]
It's probably because your agewitness is signed by a key stored on bisq, but i'm not sure that even with this key you could import the witness
