### ISSUE TITLE
Always stay at connecting to Haveno network

### ISSUE THREAD

**Issue by 0xAu** [retoaccess1/haveno-reto#31]
stuck at “Connecting to tor network 1/4”
and switch Connect with provided bridges or enter custom bridges aren't work.

By the way，I can't open https://www.torproject.org/ in Chrome browser but Tor Browser.

**Comment by XMRZombie** [comment]
Can you send your logs and what OS/Distro were you using on https://github.com/haveno-dex/haveno ?
