### ISSUE TITLE
If the network is decentralized, then how peers interconnect (no bootstrap/seed nodes)?

### ISSUE THREAD

**Issue by slrslr** [retoaccess1/haveno-reto#42]
Search "decentralized" at:
https://retoswap.com
https://github.com/retoaccess1/haveno-reto
https://docs.haveno.exchange/

I should be able to find the link to information about how the decentralization is achieved?
Someone [claimed](https://lemmings.world/post/17219117) that the order book is not decentralized.

Can it be called decentralized if there is a single point of failure?

**Comment by smarkoco** [comment]
I was also wondering how the peers are established. Would that be some sort of broadcast or would it be retrieving a list from some central server?

For example, if I’m the only person running it in the world, and a second person logs on, how do the two Tor exit nodes make a connection?

**Comment by boldsuck** [comment]
> Search "decentralized" at: https://retoswap.com https://github.com/retoaccess1/haveno-reto https://docs.haveno.exchange/

**Search and learn what a P2P network is. This is not Haveno or specific**. 
Just like Monero P2P or Bitcoin P2P. Haveno P2P is completely hidden service.
 Seed nodes are decentralized. You are welcome to run one. Let it run and get in touch with Reto Chat.

> I should be able to find the link to information about how the decentralization is achieved?
https://docs.haveno.exchange/the-project/overview/

> Someone [claimed](https://lemmings.world/post/17219117) that the order book is not decentralized.
¹

We, the **decentralized users, make the order book**. No User, no order book ;-)
stupid AI, of course you can use external wallets. Apparently you have never used the GUI before.

> Can it be called decentralized if there is a single point of failure?
Where is single point of failure?

¹Someone is probably Kewbit and Aloha, who want to SCAM Haveno users with splinter instances.
