### ISSUE TITLE
Issue updating on .deb (Linux Debian): java.io.FileNotFoundException: https://haveno.exchange/downloads/v1.0.15/Haveno-64bit-1.0.15.deb

### ISSUE THREAD

**Issue by slrslr** [retoaccess1/haveno-reto#45]
I am running 1.0.14 .deb on Linux Debian 12 (stable).

After clicking to download update within the app prompt, it apparently failed with exception in this issue title. More detailed output [is here](https://bin.disroot.org/?7ee6e381a88001a5#CekBfCMMwtwyik2tBoAtFzAa41rkgk5QEbiKMryMpb5)

**Comment by boldsuck** [comment]
The build was probably not finished yet. They're all here now.
https://github.com/retoaccess1/haveno-reto/releases/tag/v1.0.15
Otherwise, get them directly from Actions.

**Comment by retoaccess1** [comment]
Download updates from Github release or https://retoswap.com
