### ISSUE TITLE
Can't launch 1.0.15 -- blank screen

### ISSUE THREAD

**Issue by balz666** [retoaccess1/haveno-reto#46]
I don't understand why you guys make new versions mandatory. I was right in the middle of a transaction and had to redownload the new version and it doesn't work. I removed last version and installed the new one with the .deb file. When lauching Haveno (with the neat new logo) all I get is a grey window loading loading loading forever and nothing happen. The window is shown as "Untitled window". I tried to remove the new version and launch from the appimage, but still got the same result.

I'm on Linux Mint XFCE.

Please help.

![image](https://github.com/user-attachments/assets/7d8aa24c-b377-45bc-a267-c9612e91dfb0)

![image](https://github.com/user-attachments/assets/286f45a1-3a90-4553-886b-1d6be48dd690)

EDIT : When launching the .AppImage from terminal, here is the message I get:

> Dec-19 14:47:09.359 [main] INFO  haveno.common.app.Version: Version{VERSION=1.0.15, P2P_NETWORK_VERSION=A, LOCAL_DB_VERSION=1, TRADE_PROTOCOL_VERSION=1, BASE_CURRENCY_NETWORK=0, getP2PNetworkId()=0A} 
> Dec-19 14:47:09.360 [main] INFO  haveno.common.setup.CommonSetup: Path to Haveno jar file: /tmp/.mount_havenoGnyVUY/lib/app/desktop-1.0.15-SNAPSHOT-all.jar 
> Dec-19 14:47:09.370 [main] INFO  haveno.common.util.Profiler: Total memory: 64 MB; Used memory: 11.409 MB; Free memory: 52.591 MB; Max memory: 1 GB; No. of threads: 1 
> Dec-19 14:47:09.411 [main] INFO  h.core.setup.CoreNetworkCapabilities: TRADE_STATISTICS [0], TRADE_STATISTICS_2 [1], ACCOUNT_AGE_WITNESS [2], PROPOSAL [5], BLIND_VOTE [6], ACK_MSG [7], BUNDLE_OF_ENVELOPES [10], SIGNED_ACCOUNT_AGE_WITNESS [11], MEDIATION [12], REFUND_AGENT [13], TRADE_STATISTICS_HASH_UPDATE [14], NO_ADDRESS_PRE_FIX [15], TRADE_STATISTICS_3 [16] 
> Dec-19 14:47:09.443 [main] INFO  haveno.core.locale.GlobalSettings: Locale info: en_US 
> Dec-19 14:47:12.763 [JavaFX Application Thread] INFO  haveno.core.app.AvoidStandbyModeService: Started -- disabled power management via /usr/bin/systemd-inhibit --who Haveno --what sleep --why Avoid Standby --mode block tail -f /dev/null 
> Dec-19 14:47:12.787 [JavaFX Application Thread] INFO  haveno.core.app.HavenoExecutable: Account already exists, attempting to open 
> Dec-19 14:47:12.887 [JavaFX Application Thread] INFO  haveno.core.app.HavenoExecutable: Account password protected, password required 
> Dec-19 14:47:13.605 [JavaFX Application Thread] ERROR haveno.common.setup.CommonSetup: Uncaught Exception from thread **JavaFX Application Thread, error=Input stream must not be null
>  java.lang.NullPointerException: Input stream must not be null
> 	at javafx.graphics/javafx.scene.image.Image.validateInputStream(Unknown Source)
> 	at javafx.graphics/javafx.scene.image.Image.<init>(Unknown Source)
> 	at haveno.desktop.util.ImageUtil.getImageByUrl(ImageUtil.java:52)
> 	at haveno.desktop.util.ImageUtil.getImageByPath(ImageUtil.java:70)
> 	at haveno.desktop.app.HavenoAppMain$PasswordDialog.<init>(HavenoAppMain.java:203)
> 	at haveno.desktop.app.HavenoAppMain.lambda$loginAccount$1(HavenoAppMain.java:174)
> 	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
> 	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
> 	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
> 	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
> 	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
> 	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(Unknown Source)
> 	at java.base/java.lang.Thread.run(Unknown Source)**
> 
> java.lang.NullPointerException: Input stream must not be null
> 	at javafx.graphics/javafx.scene.image.Image.validateInputStream(Unknown Source)
> 	at javafx.graphics/javafx.scene.image.Image.<init>(Unknown Source)
> 	at haveno.desktop.util.ImageUtil.getImageByUrl(ImageUtil.java:52)
> 	at haveno.desktop.util.ImageUtil.getImageByPath(ImageUtil.java:70)
> 	at haveno.desktop.app.HavenoAppMain$PasswordDialog.<init>(HavenoAppMain.java:203)
> 	at haveno.desktop.app.HavenoAppMain.lambda$loginAccount$1(HavenoAppMain.java:174)
> 	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
> 	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
> 	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
> 	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
> 	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
> 	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(Unknown Source)
> 	at java.base/java.lang.Thread.run(Unknown Source)
> **Dec-19 14:47:13.627 [JavaFX Application Thread] WARN  haveno.desktop.app.HavenoApp: Scene not available yet, we create a new scene. The bug might be caused by an exception in a constructor or by a circular dependency in Guice. throwable=java.lang.NullPointerException: Input stream must not be null** 

What is shown in **bold** is in red in my terminal.

**Comment by haveno751** [comment]
Same problem, same error. Possibly worth noting: If it's a new install of haveno, it will launch. However, once a password is set, and it is relaunched, it will *not* present the password entry window. Instead it shows the blank window.

**Comment by balz666** [comment]
Any chance for a fix soon?

**Comment by retoaccess1** [comment]
> Any chance for a fix soon? We can't be only two with this bug. I need to log back in ASAP.

Install latest version for fix (v16).
