### ISSUE TITLE
Issue with breaking profile in RetoSwap 1.0.15+?

### ISSUE THREAD

**Issue by slrslr** [retoaccess1/haveno-reto#48]
In v.1.0.15 I have seen a pop-up warning about the bug which causes breaking of a user profile.
Can you update this issue once that bug is fixed?

**Comment by boldsuck** [comment]
If you had a pop-up warning in Haveno, you were not affected by the Wallet Passwort bug.
Bug was already fixed 8 hours ago when you wrote this issue.
https://github.com/retoaccess1/haveno-reto/releases/tag/v1.0.16
