### ISSUE TITLE
Can only trade one pair LTCXMR

### ISSUE THREAD

**Issue by Synthacon** [retoaccess1/haveno-reto#9]
Only one currency pair LTCXMR is available  for trading, all other pairs are grayed out and clicking them shows "No matching payment account..." box.  I have added addresses for all coins. I have deposited small amount of XMR, this has no effect on anything. 

![Screenshot from 2024-07-17 21-03-50](https://github.com/user-attachments/assets/90a6a849-9821-43bd-9eae-5347f31fa96f)
![Screenshot from 2024-07-17 21-04-40](https://github.com/user-attachments/assets/acfef736-e68b-4f4e-b99d-d7ad675d4c50)
![Screenshot from 2024-07-17 21-09-19](https://github.com/user-attachments/assets/77b47d5a-914b-4d97-9a20-f1e92a5dd3a6)

**Comment by retoaccess1** [comment]
Hello, are you sure you are on the right tab? Your last screenshot shows you on the fiat page but you need to go to "SELL" and then "OTHER" (Sell other assets for Monero). The wording is a bit weird, you would of course expect to buy Monero on the buy tab, which is not the case.

**Comment by Synthacon** [comment]
btw this is Ubuntu version. I installed Windows version and it seems to work fine.

**Comment by Synthacon** [comment]
Updated to 1.0.9,   deleted all cryptocurrency accounts and added them again and now everything works.
